services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: scrapper
      POSTGRES_PASSWORD: scrapper
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scrapper -d scrapper"]
      interval: 5s
      timeout: 3s
      retries: 10

  kafka-1:
    image: confluentinc/cp-kafka:7.6.1
    hostname: kafka-1
    container_name: kafka-1
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"

      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-1:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"

      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:29093"

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_MIN_INSYNC_REPLICAS: "1"

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"

  kafka-init:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - kafka-1
    entrypoint: ["/bin/bash", "-c"]
    command: |
      echo 'Waiting for Kafka...'

      until kafka-topics --bootstrap-server kafka-1:29092 --list >/dev/null 2>&1; do
        echo 'Kafka is not ready yet...'
        sleep 2
      done

      echo 'Creating topics...'

      kafka-topics --bootstrap-server kafka-1:29092 \
        --create --if-not-exists \
        --topic link-updates \
        --partitions 6 \
        --replication-factor 1

      kafka-topics --bootstrap-server kafka-1:29092 \
        --create --if-not-exists \
        --topic link-updates-dlq \
        --partitions 6 \
        --replication-factor 1

      echo 'Topics:'
      kafka-topics --bootstrap-server kafka-1:29092 --list

      echo 'link-updates description:'
      kafka-topics --bootstrap-server kafka-1:29092 --describe --topic link-updates

      echo 'Done.'
    restart: "no"
