server:
  port: 8081

spring:
  application:
    name: scrapper
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/scrapper}
    username: ${POSTGRES_USER:scrapper}
    password: ${POSTGRES_PASSWORD:scrapper}
  liquibase:
    enabled: true
    change-log: classpath:/migrations/changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate

app:
  database:
    access-type: ${ACCESS_TYPE:SQL}
  stackoverflow:
    key: ${STACKOVERFLOW_KEY:}
    access-token: ${STACKOVERFLOW_ACCESS_KEY:}
  github:
    token: ${GITHUB_TOKEN:}
  bot:
    base-url: ${BOT_BASE_URL:http://localhost:8080}
  scheduler:
    interval: 30s
